program GenericDataTypes;

uses
  System.StartUpCopy,
  FMX.Forms,
  Connection.Types in '..\Source\Connection\Connection.Types.pas',
  Connection.IConnectionStrategy in '..\Source\Connection\Strategy\Connection.IConnectionStrategy.pas',
  Connection.IQueryStrategy in '..\Source\Connection\Strategy\Connection.IQueryStrategy.pas',
  Connection.IEngineFactory in '..\Source\Connection\Strategy\Connection.IEngineFactory.pas',
  Connection.IDriverConfigurator in '..\Source\Connection\Strategy\Connection.IDriverConfigurator.pas',
  EngineRegistry in '..\Source\Connection\Registry\EngineRegistry.pas',
  FireDAC.Factory in '..\Source\Connection\Adapters\FireDAC\FireDAC.Factory.pas',
  FireDAC.ConnectionStrategy in '..\Source\Connection\Adapters\FireDAC\FireDAC.ConnectionStrategy.pas',
  FireDAC.QueryStrategy in '..\Source\Connection\Adapters\FireDAC\FireDAC.QueryStrategy.pas',
  FireDAC.Driver.SQLite in '..\Source\Connection\Adapters\FireDAC\FireDAC.Driver.SQLite.pas',
  FireDAC.Driver.MySQL in '..\Source\Connection\Adapters\FireDAC\FireDAC.Driver.MySQL.pas',
  FireDAC.Driver.Firebird in '..\Source\Connection\Adapters\FireDAC\FireDAC.Driver.Firebird.pas',
  FireDAC.Driver.Interbase in '..\Source\Connection\Adapters\FireDAC\FireDAC.Driver.Interbase.pas',
  FireDAC.Driver.MSSQL in '..\Source\Connection\Adapters\FireDAC\FireDAC.Driver.MSSQL.pas',
  FireDAC.Driver.PostgreSQL in '..\Source\Connection\Adapters\FireDAC\FireDAC.Driver.PostgreSQL.pas',
  FireDAC.Driver.Oracle in '..\Source\Connection\Adapters\FireDAC\FireDAC.Driver.Oracle.pas',
  Connection.Intf in '..\Source\Connection\Connection.Intf.pas',
  Connection in '..\Source\Connection\Connection.pas',
  Locale in '..\Source\Types\Locale\Locale.pas',
  RTTI in '..\Source\Reflection\RTTI.pas',
  XSuperJSON in '..\Source\Vendor\XSuperObject\XSuperJSON.pas',
  XSuperObject in '..\Source\Vendor\XSuperObject\XSuperObject.pas',
  FMX.FireMonkey.Parser in '..\Source\Helpers\FMX.ListView\FMX.FireMonkey.Parser.pas',
  FMX.ListView in '..\Source\Helpers\FMX.ListView\FMX.ListView.pas',
  FMX.ListView.TextButtonFix in '..\Source\Helpers\FMX.ListView\FMX.ListView.TextButtonFix.pas',
  FMX.ListView.Types in '..\Source\Helpers\FMX.ListView\FMX.ListView.Types.pas',
  FMX.ListView.Extension in '..\Source\Helpers\FMX.ListView\FMX.ListView.Extension.pas',
  FMX.Edit.Suggest.Messages in '..\Source\Helpers\FMX.Edit\FMX.Edit.Suggest.Messages.pas',
  FMX.Edit.Extension in '..\Source\Helpers\FMX.Edit\FMX.Edit.Extension.pas',
  FMX.Grid.Helper in '..\Source\Helpers\FMX.Grid\FMX.Grid.Helper.pas',
  FMX.ListBox.Helper in '..\Source\Helpers\FMX.ListBox\FMX.ListBox.Helper.pas',
  FMX.ListView.Helper in '..\Source\Helpers\FMX.ListView\FMX.ListView.Helper.pas',
  FMX.StringGrid.Helper in '..\Source\Helpers\FMX.StringGrid\FMX.StringGrid.Helper.pas',
  FMX.Edit.Helper in '..\Source\Helpers\FMX.Edit\FMX.Edit.Helper.pas',
  EventDelegate in '..\Source\Helpers\EventDelegate\EventDelegate.pas',
  EventDriven.Types in '..\Source\EventDriven\EventDriven.Types.pas',
  EventDriven.Core in '..\Source\EventDriven\EventDriven.Core.pas',
  EventDriven.Notify in '..\Source\EventDriven\EventDriven.Notify.pas',
  EventDriven.Key in '..\Source\EventDriven\EventDriven.Key.pas',
  EventDriven.ItemBox in '..\Source\EventDriven\EventDriven.ItemBox.pas',
  EventDriven.ItemView in '..\Source\EventDriven\EventDriven.ItemView.pas',
  EventDriven.Paint in '..\Source\EventDriven\EventDriven.Paint.pas',
  EventDriven.ItemButton in '..\Source\EventDriven\EventDriven.ItemButton.pas',
  EventDriven.ItemUpdating in '..\Source\EventDriven\EventDriven.ItemUpdating.pas',
  EventDriven.GridBindings in '..\Source\EventDriven\EventDriven.GridBindings.pas',
  EventDriven in '..\Source\EventDriven\EventDriven.pas',
  FMX.ComboEdit.Helper in '..\Source\Helpers\FMX.ComboEdit\FMX.ComboEdit.Helper.pas',
  FMX.ComboBox.Helper in '..\Source\Helpers\FMX.ComboBox\FMX.ComboBox.Helper.pas',
  FMX.Objects.Helper in '..\Source\Helpers\FMX.Objects\FMX.Objects.Helper.pas',
  DictionaryHelper in '..\Source\Helpers\DictionaryHelper\DictionaryHelper.pas',
  ArrayHelper in '..\Source\Helpers\ArrayHelper\ArrayHelper.pas',
  MimeType in '..\Source\Reflection\MimeType.pas',
  TimeDate in '..\Source\Types\TimeDate.pas',
  Float in '..\Source\Types\Float.pas',
  Strings in '..\Source\Types\Strings.pas',
  ArrayAssoc in '..\Source\Types\Array\ArrayAssoc.pas',
  ArrayField in '..\Source\Types\Array\ArrayField.pas',
  ArrayString in '..\Source\Types\Array\ArrayString.pas',
  ArrayVariant in '..\Source\Types\Array\ArrayVariant.pas',
  ArrayFieldHelper in '..\Source\Types\Array\Helpers\ArrayFieldHelper.pas',
  ArrayStringHelper in '..\Source\Types\Array\Helpers\ArrayStringHelper.pas',
  ArrayVariantHelper in '..\Source\Types\Array\Helpers\ArrayVariantHelper.pas',
  Query.Intf in '..\Source\Connection\Query.Intf.pas',
  Query in '..\Source\Connection\Query.pas',
  QueryBuilder in '..\Source\Connection\QueryBuilder.pas',
  Connector.Types in '..\Source\Connector\Connector.Types.pas',
  Connector.Intf in '..\Source\Connector\Connector.Intf.pas',
  Connector in '..\Source\Connector\Connector.pas',
  Options.Intf in '..\Source\Connector\Options\Options.Intf.pas',
  OptionsInteger in '..\Source\Connector\Options\OptionsInteger.pas',
  OptionsArray in '..\Source\Connector\Options\OptionsArray.pas',
  OptionsJSON in '..\Source\Connector\Options\OptionsJSON.pas',
  IArray in '..\Source\Types\IArray.pas',
  SmartPointer.IGuard.Intf in '..\Source\SmartPointer\SmartPointer.IGuard.Intf.pas',
  SmartPointer.Guard in '..\Source\SmartPointer\SmartPointer.Guard.pas',
  SmartPointer.ISmartPointer in '..\Source\SmartPointer\SmartPointer.ISmartPointer.pas',
  SmartPointer.RefGuard in '..\Source\SmartPointer\SmartPointer.RefGuard.pas',
  SmartPointer.TSmartPointer in '..\Source\SmartPointer\SmartPointer.TSmartPointer.pas',
  GenericDataTypesForm in 'GenericDataTypesForm.pas' {GenericDataTypesForm};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TGenericDataTypesForm, FGenericDataTypesForm);
  Application.Run;
end.
